version: "3"
services:
  php:
    build:
      context: ./php
    ports:
      - "8080:80"
    tty: true
    stdin_open: true
    volumes:
      - ./src:/src
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini